from dataclasses import dataclass
from datetime import datetime
from typing import Optional

STATUS = {
    "open": "Open",
    "escalated": "Escalated to Technical Team",
    "resolved": "Resolved",
}

ASSIGNED_TO = {
    "lmbot": "LMBot",
    "technical_team": "Technical Team",
}


@dataclass
class Ticket:
    id: Optional[str]
    session_id: Optional[str]  # nullable — ticket survives session deletion
    user_id: str
    summary: Optional[str]  # generated by LLM at escalation time
    status: str  # "open" | "escalated" | "resolved"
    assigned_to: str  # "lmbot" | "technical_team"
    created_at: datetime
    updated_at: datetime
